language: ruby
script: "bundle exec rake spec"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - rbx-2.2.10
  - 2.1.3
notifications:
  recipients:
    - peter.schrammel@experteer.com
branches:
  only:
    - master
    - rails32


